// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reviews.proto

package reviews

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateReviewRequest struct {
	Review               *Review  `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReviewRequest) Reset()         { *m = CreateReviewRequest{} }
func (m *CreateReviewRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReviewRequest) ProtoMessage()    {}
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b2a6bc9211d2c89, []int{0}
}

func (m *CreateReviewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReviewRequest.Unmarshal(m, b)
}
func (m *CreateReviewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReviewRequest.Marshal(b, m, deterministic)
}
func (m *CreateReviewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReviewRequest.Merge(m, src)
}
func (m *CreateReviewRequest) XXX_Size() int {
	return xxx_messageInfo_CreateReviewRequest.Size(m)
}
func (m *CreateReviewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReviewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReviewRequest proto.InternalMessageInfo

func (m *CreateReviewRequest) GetReview() *Review {
	if m != nil {
		return m.Review
	}
	return nil
}

type CreateReviewResponse struct {
	Succes               bool     `protobuf:"varint,1,opt,name=succes,proto3" json:"succes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReviewResponse) Reset()         { *m = CreateReviewResponse{} }
func (m *CreateReviewResponse) String() string { return proto.CompactTextString(m) }
func (*CreateReviewResponse) ProtoMessage()    {}
func (*CreateReviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b2a6bc9211d2c89, []int{1}
}

func (m *CreateReviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReviewResponse.Unmarshal(m, b)
}
func (m *CreateReviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReviewResponse.Marshal(b, m, deterministic)
}
func (m *CreateReviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReviewResponse.Merge(m, src)
}
func (m *CreateReviewResponse) XXX_Size() int {
	return xxx_messageInfo_CreateReviewResponse.Size(m)
}
func (m *CreateReviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReviewResponse proto.InternalMessageInfo

func (m *CreateReviewResponse) GetSucces() bool {
	if m != nil {
		return m.Succes
	}
	return false
}

type Review struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId               int32    `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Rating               int32    `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b2a6bc9211d2c89, []int{2}
}

func (m *Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Review.Unmarshal(m, b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Review.Marshal(b, m, deterministic)
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return xxx_messageInfo_Review.Size(m)
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Review) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *Review) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Review) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetRatingByItemIdRequest struct {
	ItemId               int32    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRatingByItemIdRequest) Reset()         { *m = GetRatingByItemIdRequest{} }
func (m *GetRatingByItemIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetRatingByItemIdRequest) ProtoMessage()    {}
func (*GetRatingByItemIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b2a6bc9211d2c89, []int{3}
}

func (m *GetRatingByItemIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatingByItemIdRequest.Unmarshal(m, b)
}
func (m *GetRatingByItemIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatingByItemIdRequest.Marshal(b, m, deterministic)
}
func (m *GetRatingByItemIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatingByItemIdRequest.Merge(m, src)
}
func (m *GetRatingByItemIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetRatingByItemIdRequest.Size(m)
}
func (m *GetRatingByItemIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatingByItemIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatingByItemIdRequest proto.InternalMessageInfo

func (m *GetRatingByItemIdRequest) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type GetRatingByItemIdResponse struct {
	Rating               float32  `protobuf:"fixed32,1,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRatingByItemIdResponse) Reset()         { *m = GetRatingByItemIdResponse{} }
func (m *GetRatingByItemIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetRatingByItemIdResponse) ProtoMessage()    {}
func (*GetRatingByItemIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b2a6bc9211d2c89, []int{4}
}

func (m *GetRatingByItemIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatingByItemIdResponse.Unmarshal(m, b)
}
func (m *GetRatingByItemIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatingByItemIdResponse.Marshal(b, m, deterministic)
}
func (m *GetRatingByItemIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatingByItemIdResponse.Merge(m, src)
}
func (m *GetRatingByItemIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetRatingByItemIdResponse.Size(m)
}
func (m *GetRatingByItemIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatingByItemIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatingByItemIdResponse proto.InternalMessageInfo

func (m *GetRatingByItemIdResponse) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateReviewRequest)(nil), "CreateReviewRequest")
	proto.RegisterType((*CreateReviewResponse)(nil), "CreateReviewResponse")
	proto.RegisterType((*Review)(nil), "Review")
	proto.RegisterType((*GetRatingByItemIdRequest)(nil), "GetRatingByItemIdRequest")
	proto.RegisterType((*GetRatingByItemIdResponse)(nil), "GetRatingByItemIdResponse")
}

func init() { proto.RegisterFile("reviews.proto", fileDescriptor_5b2a6bc9211d2c89) }

var fileDescriptor_5b2a6bc9211d2c89 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x95, 0x0b, 0x38, 0x70, 0xc0, 0x80, 0x29, 0xe0, 0x66, 0xa1, 0xf2, 0xd4, 0xc9, 0x43, 0x23,
	0xb1, 0xb0, 0xc1, 0x80, 0xc2, 0xe8, 0x3f, 0x80, 0x42, 0x73, 0xaa, 0x22, 0xd1, 0xa6, 0xf8, 0x1c,
	0x10, 0x7f, 0x83, 0x5f, 0x8c, 0xfc, 0x11, 0x11, 0x44, 0x3a, 0xbe, 0x7b, 0xef, 0xf9, 0xee, 0x3d,
	0xc3, 0xb9, 0xc5, 0x8f, 0x06, 0x3f, 0x49, 0xef, 0x6c, 0xeb, 0x5a, 0x75, 0x07, 0x97, 0x8f, 0x16,
	0x2b, 0x87, 0x26, 0x8c, 0x0d, 0xbe, 0x77, 0x48, 0x4e, 0xdc, 0x02, 0x8f, 0x3a, 0xc9, 0xe6, 0x6c,
	0x71, 0xba, 0xcc, 0x74, 0xe2, 0xd3, 0x58, 0x69, 0x98, 0xfe, 0xf5, 0xd1, 0xae, 0xdd, 0x12, 0x8a,
	0x6b, 0xe0, 0xd4, 0xad, 0x56, 0x48, 0xc1, 0x78, 0x6c, 0x12, 0x52, 0x6f, 0xc0, 0xa3, 0x52, 0xdc,
	0x40, 0xd6, 0x11, 0xda, 0x97, 0xa6, 0x0e, 0x92, 0x23, 0xc3, 0x3d, 0x2c, 0x6b, 0x4f, 0x34, 0x0e,
	0x37, 0x9e, 0x98, 0x44, 0xc2, 0xc3, 0xb2, 0xf6, 0x6f, 0xda, 0xca, 0x35, 0xdb, 0xb5, 0x3c, 0x88,
	0xf3, 0x88, 0x84, 0x84, 0x6c, 0x83, 0x44, 0xd5, 0x1a, 0xe5, 0xe1, 0x9c, 0x2d, 0x4e, 0x4c, 0x0f,
	0x55, 0x01, 0xf2, 0x09, 0x9d, 0x09, 0xb2, 0x87, 0xaf, 0x32, 0x3c, 0xd3, 0x47, 0x1b, 0xac, 0x61,
	0xc3, 0x35, 0xaa, 0x80, 0xd9, 0x88, 0xe9, 0x37, 0x57, 0xba, 0xc1, 0x9b, 0x26, 0xfd, 0x0d, 0xcb,
	0x6f, 0x06, 0x59, 0x0c, 0x46, 0xe2, 0x1e, 0xce, 0x86, 0x9d, 0x88, 0xa9, 0x1e, 0xa9, 0x36, 0xbf,
	0xd2, 0xa3, 0xc5, 0x3d, 0xc3, 0xc5, 0xbf, 0xed, 0x62, 0xa6, 0xf7, 0xc5, 0xc8, 0x73, 0xbd, 0xf7,
	0xd8, 0x57, 0x1e, 0xfe, 0xb6, 0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x7e, 0xe7, 0x50, 0xec,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReviewsClient is the client API for Reviews service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReviewsClient interface {
	CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*CreateReviewResponse, error)
	GetRatingByItemId(ctx context.Context, in *GetRatingByItemIdRequest, opts ...grpc.CallOption) (*GetRatingByItemIdResponse, error)
}

type reviewsClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewsClient(cc grpc.ClientConnInterface) ReviewsClient {
	return &reviewsClient{cc}
}

func (c *reviewsClient) CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*CreateReviewResponse, error) {
	out := new(CreateReviewResponse)
	err := c.cc.Invoke(ctx, "/Reviews/CreateReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsClient) GetRatingByItemId(ctx context.Context, in *GetRatingByItemIdRequest, opts ...grpc.CallOption) (*GetRatingByItemIdResponse, error) {
	out := new(GetRatingByItemIdResponse)
	err := c.cc.Invoke(ctx, "/Reviews/GetRatingByItemId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewsServer is the server API for Reviews service.
type ReviewsServer interface {
	CreateReview(context.Context, *CreateReviewRequest) (*CreateReviewResponse, error)
	GetRatingByItemId(context.Context, *GetRatingByItemIdRequest) (*GetRatingByItemIdResponse, error)
}

// UnimplementedReviewsServer can be embedded to have forward compatible implementations.
type UnimplementedReviewsServer struct {
}

func (*UnimplementedReviewsServer) CreateReview(ctx context.Context, req *CreateReviewRequest) (*CreateReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReview not implemented")
}
func (*UnimplementedReviewsServer) GetRatingByItemId(ctx context.Context, req *GetRatingByItemIdRequest) (*GetRatingByItemIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRatingByItemId not implemented")
}

func RegisterReviewsServer(s *grpc.Server, srv ReviewsServer) {
	s.RegisterService(&_Reviews_serviceDesc, srv)
}

func _Reviews_CreateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServer).CreateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Reviews/CreateReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServer).CreateReview(ctx, req.(*CreateReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reviews_GetRatingByItemId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatingByItemIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServer).GetRatingByItemId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Reviews/GetRatingByItemId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServer).GetRatingByItemId(ctx, req.(*GetRatingByItemIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reviews_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Reviews",
	HandlerType: (*ReviewsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReview",
			Handler:    _Reviews_CreateReview_Handler,
		},
		{
			MethodName: "GetRatingByItemId",
			Handler:    _Reviews_GetRatingByItemId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reviews.proto",
}
